### PR TITLE
DEVTOOLS-602 Support release-on-merge autofix

### PR DESCRIPTION
**Pull request by jimmylai**

### CODE REVIEW

**Comment by EricVogl-carta** [comment]
What does `release-on-merge` do? The Jira doesn't have any details.

**Review by rodrigorbl — APPROVED** [review]

**Comment by rodrigorbl** [comment]
What happens if we run this on `carta-web` repository?

**Comment by EricVogl-carta** [comment]
@jimmylai this was merged without responding to my question. Can we get visibility on that? Also how did this merge without codeowner approval?

**Comment by jimmylai** [comment]
> 

@EricVogl-carta I replied to you twice on the other PR and it's approved by a codeowner.

**Pull request merged**
